devel/urls.py
from django.urls import path, re_path

from devel import views

urlpatterns = [
    path('admin_log/', views.admin_log),
    re_path(r'^admin_log/(?P<username>.*)/$', views.admin_log),
    path('clock/',    views.clock, name='devel-clocks'),
    path('tier0mirror/',    views.tier0_mirror, name='tier0-mirror'),
    path('mirrorauth/',    views.tier0_mirror_auth, name='tier0-mirror-atuh'),
    path('',          views.index, name='devel-index'),
    path('stats/',    views.stats, name='devel-stats'),
    path('newuser/',  views.new_user_form),
    path('profile/',  views.change_profile),
    re_path(r'^reports/(?P<report_name>.*)/(?P<username>.*)/$', views.report),
    re_path(r'^reports/(?P<report_name>.*)/$', views.report),
]

# vim: set ts=4 sw=4 et:

urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.sitemaps import views as sitemap_views
from django.urls import include, path, re_path
from django.views.decorators.cache import cache_page
from django.views.generic import TemplateView

import devel.urls
import mirrors.urls
import mirrors.urls_mirrorlist
import news.urls
import packages.urls
import packages.urls_groups
import packages.views
import planet.views
import public.views
import releng.urls
import sitemaps
import todolists.urls
import visualize.urls
from feeds import NewsFeed, PackageFeed, PackageUpdatesFeed, PlanetFeed, ReleaseFeed

our_sitemaps = {
    'base':           sitemaps.BaseSitemap,
    'news':           sitemaps.NewsSitemap,
    'packages':       sitemaps.PackagesSitemap,
    'package-files':  sitemaps.PackageFilesSitemap,
    'package-groups': sitemaps.PackageGroupsSitemap,
    'split-packages': sitemaps.SplitPackagesSitemap,
    'releases':       sitemaps.ReleasesSitemap,
    'todolists':      sitemaps.TodolistSitemap,
}

news_sitemaps = {'news': sitemaps.RecentNewsSitemap}

urlpatterns = []

# Public pages
urlpatterns.extend([
    path('', public.views.index, name='index'),
    path('about/', TemplateView.as_view(template_name='public/about.html'), name='page-about'),
    path('art/',   TemplateView.as_view(template_name='public/art.html'), name='page-art'),
    path('donate/', public.views.donate, name='page-donate'),
    path('download/', public.views.download, name='page-download'),
    path('master-keys/', public.views.keys, name='page-keys'),
    path('master-keys/json/', public.views.keys_json, name='pgp-keys-json'),
    re_path(r'^people/(?P<slug>[-\w]+)/$', public.views.people, name='people'),
    path('planet/', planet.views.index, name='planet'),
])

# Feeds patterns, used below
feeds_patterns = [
    path('', public.views.feeds, name='feeds-list'),
    path('news/', cache_page(311)(NewsFeed())),
    path('packages/', cache_page(313)(PackageFeed())),
    re_path(r'^packages/(added|removed)/$', cache_page(313)(PackageUpdatesFeed())),
    re_path(r'^packages/(added|removed)/(?P<arch>[A-z0-9]+)/$', cache_page(313)(PackageUpdatesFeed())),
    re_path(r'^packages/(added|removed)/all/(?P<repo>[A-z0-9\-]+)/$', cache_page(313)(PackageUpdatesFeed())),
    re_path(r'^packages/(added|removed)/(?P<arch>[A-z0-9]+)/(?P<repo>[A-z0-9\-]+)/$',
            cache_page(313)(PackageUpdatesFeed())),
    re_path(r'^packages/(?P<arch>[A-z0-9]+)/$', cache_page(313)(PackageFeed())),
    re_path(r'^packages/all/(?P<repo>[A-z0-9\-]+)/$', cache_page(313)(PackageFeed())),
    re_path(r'^packages/(?P<arch>[A-z0-9]+)/(?P<repo>[A-z0-9\-]+)/$', cache_page(313)(PackageFeed())),
    path('releases/', cache_page(317)(ReleaseFeed())),
    path('planet/', cache_page(317)(PlanetFeed()), name='planet-feed'),
]

# Old planet.archlinux.org redirects, to be removed once people have migrated.
urlpatterns.extend([
    path('planet/rss20.xml', cache_page(317)(PlanetFeed())),
    path('planet/atom.xml', cache_page(317)(PlanetFeed())),
])

# Includes and other remaining stuff
urlpatterns.extend([
    path('admin/', admin.site.urls),
    path('devel/', include(devel.urls)),
    path('feeds/', include(feeds_patterns)),
    path('groups/', include(packages.urls_groups)),
    path('mirrorlist/', include(mirrors.urls_mirrorlist)),
    path('mirrors/', include(mirrors.urls)),
    path('news/', include(news.urls)),
    path('packages/', include(packages.urls)),
    path('releng/', include(releng.urls)),
    path('todo/', include(todolists.urls)),
    path('visualize/', include(visualize.urls)),
    path('opensearch/packages/', packages.views.opensearch, name='opensearch-packages'),
    path('opensearch/packages/suggest', packages.views.opensearch_suggest, name='opensearch-packages-suggest'),
])

# Sitemaps
urlpatterns.extend([
    path('sitemap.xml', cache_page(1831)(sitemap_views.index),
         {'sitemaps': our_sitemaps, 'sitemap_url_name': 'sitemaps'}),
    re_path(r'^sitemap-(?P<section>.+)\.xml$', cache_page(1831)(sitemap_views.sitemap),
            {'sitemaps': our_sitemaps, 'template_name': 'sitemaps/sitemap.xml'},
            name='sitemaps'),
    path('news-sitemap.xml', cache_page(1831)(sitemap_views.sitemap),
         {'sitemaps': news_sitemaps, 'template_name': 'sitemaps/news_sitemap.xml'},
         name='news-sitemap'),
])

# Authentication
urlpatterns.extend([
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
])

# django-toolbar
if settings.DEBUG_TOOLBAR:  # pragma: no cover
    import debug_toolbar
    urlpatterns.extend([
        path('__debug__/', include(debug_toolbar.urls)),
    ])

# prometheus metrics
if settings.PROMETHEUS_METRICS:  # pragma :no cover
    urlpatterns.extend([
        path('', include('django_prometheus.urls')),
    ])


# displays all archweb urls
def show_urls(urllist=urlpatterns, depth=0):  # pragma: no cover
    for entry in urllist:
        print("  " * depth, entry.regex.pattern)
        if hasattr(entry, 'url_patterns'):
            show_urls(entry.url_patterns, depth + 1)

# vim: set ts=4 sw=4 et:

main/models.py
from datetime import datetime, timezone
from itertools import groupby

from django.contrib.auth.models import User
from django.contrib.sites.models import Site
from django.db import models
from django.db.models import Q
from pgpdump import BinaryData

from devel.models import DeveloperKey
from packages.alpm import AlpmAPI

from .utils import DependStandin, SignatureWrapper, set_created_field


class PackageManager(models.Manager):
    def flagged(self):
        """Used by dev dashboard."""
        return self.filter(flag_date__isnull=False)

    def normal(self):
        return self.select_related('arch', 'repo')

    def restricted(self, user=None):
        qs = self.normal()
        if user is not None and user.is_authenticated:
            return qs
        return qs.filter(repo__staging=False)


class Donor(models.Model):
    name = models.CharField(max_length=255, unique=True)
    visible = models.BooleanField(
        default=True, help_text="Should we show this donor on the public page?")
    created = models.DateTimeField()

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'donors'
        ordering = ('name',)
        get_latest_by = 'created'


class Arch(models.Model):
    name = models.CharField(max_length=255, unique=True)
    agnostic = models.BooleanField(
        default=False, help_text="Is this architecture non-platform specific?")
    required_signoffs = models.PositiveIntegerField(
        default=2, help_text="Number of signoffs required for packages of this architecture")

    def __str__(self):
        return self.name

    def __lt__(self, other):
        return self.name < other.name

    class Meta:
        db_table = 'arches'
        ordering = ('name',)
        verbose_name_plural = 'arches'


class Repo(models.Model):
    name = models.CharField(max_length=255, unique=True)
    testing = models.BooleanField(
        default=False, help_text="Is this repo meant for package testing?")
    public_testing = models.BooleanField(
        default=False, help_text="Is this repo meant for package testing (without signoffs)?")
    staging = models.BooleanField(
        default=False, help_text="Is this repo meant for package staging?")
    bugs_project = models.SmallIntegerField(
        default=1, help_text="Flyspray project ID for this repository.")
    bugs_category = models.SmallIntegerField(
        default=2, help_text="Flyspray category ID for this repository.")
    svn_root = models.CharField(
        max_length=64, help_text="SVN root (e.g. path) for this repository.")

    def __str__(self):
        return self.name

    def __lt__(self, other):
        return self.name < other.name

    class Meta:
        db_table = 'repos'
        ordering = ('name',)


class Package(models.Model):
    repo = models.ForeignKey(Repo, related_name="packages", on_delete=models.PROTECT)
    arch = models.ForeignKey(Arch, related_name="packages", on_delete=models.PROTECT)
    pkgname = models.CharField(max_length=255)
    pkgbase = models.CharField(max_length=255, db_index=True)
    pkgver = models.CharField(max_length=255)
    pkgrel = models.CharField(max_length=255)
    epoch = models.PositiveIntegerField(default=0)
    pkgdesc = models.TextField('description', null=True)
    url = models.CharField('URL', max_length=255, null=True)
    filename = models.CharField(max_length=255)
    compressed_size = models.PositiveBigIntegerField()
    installed_size = models.PositiveBigIntegerField()
    build_date = models.DateTimeField(null=True)
    last_update = models.DateTimeField(db_index=True)
    files_last_update = models.DateTimeField(null=True, blank=True)
    created = models.DateTimeField()
    packager_str = models.CharField('packager string', max_length=255)
    packager = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    signature_bytes = models.BinaryField('PGP signature', null=True)
    flag_date = models.DateTimeField(null=True, blank=True)

    objects = PackageManager()

    class Meta:
        db_table = 'packages'
        ordering = ('pkgname',)
        get_latest_by = 'last_update'
        unique_together = (('pkgname', 'repo', 'arch'),)

    def __str__(self):
        return self.pkgname

    @property
    def full_version(self):
        if self.epoch > 0:
            return '%d:%s-%s' % (self.epoch, self.pkgver, self.pkgrel)
        return '%s-%s' % (self.pkgver, self.pkgrel)

    def get_absolute_url(self):
        return f'/packages/{self.repo.name.lower()}/{self.arch.name}/{self.pkgname}/'

    def get_full_url(self, proto='https'):
        '''get a URL suitable for things like email including the domain'''
        domain = Site.objects.get_current().domain
        return f'{proto}://{domain}{self.get_absolute_url()}'

    @property
    def updated_mins_ago(self):
        # Note: This uses the archweb metadata update time, not when the
        # package was actually pushed to any repo. We don't have that
        # easily available without adding more fields and scripts.
        # See: https://github.com/archlinux/archweb/pull/323
        now = datetime.now(timezone.utc)
        return int((now - self.last_update).total_seconds()) // 60

    @property
    def is_recent(self):
        return self.updated_mins_ago <= 90

    @property
    def signature(self):
        if not self.signature_bytes:
            return None
        data = BinaryData(self.signature_bytes)
        packets = list(data.packets())
        return SignatureWrapper(packets[0])

    @property
    def signer(self):
        sig = self.signature
        if sig and sig.key_id:
            try:
                matching_key = DeveloperKey.objects.select_related(
                    'owner').get(key=sig.key_id, owner_id__isnull=False)
                user = matching_key.owner
            except DeveloperKey.DoesNotExist:
                user = None
            return user
        return None

    _maintainers = None

    @property
    def maintainers(self):
        from packages.models import PackageRelation
        if self._maintainers is None:
            self._maintainers = User.objects.filter(
                package_relations__pkgbase=self.pkgbase,
                package_relations__type=PackageRelation.MAINTAINER)
        return self._maintainers

    @maintainers.setter
    def maintainers(self, maintainers):
        self._maintainers = maintainers

    _applicable_arches = None

    def applicable_arches(self):
        '''The list of (this arch) + (available agnostic arches).'''
        if self._applicable_arches is None:
            arches = set(Arch.objects.filter(agnostic=True))
            arches.add(self.arch)
            self._applicable_arches = list(arches)
        return self._applicable_arches

    def get_requiredby(self):
        """
        Returns a list of package objects. An attempt will be made to keep this
        list slim by including the corresponding package in the same testing
        category as this package if that check makes sense.
        """
        from packages.models import Depend
        sorttype = '''(CASE deptype
        WHEN 'D' THEN 0
        WHEN 'O' THEN 1
        WHEN 'M' THEN 2
        WHEN 'C' THEN 3
        ELSE 1000 END)'''
        name_clause = '''packages_depend.name IN (
        SELECT %s UNION ALL
        SELECT z.name FROM packages_provision z WHERE z.pkg_id = %s
        )'''
        requiredby = Depend.objects.select_related(
            'pkg', 'pkg__arch', 'pkg__repo').extra(
            select={'sorttype': sorttype},
            where=[name_clause], params=[self.pkgname, self.id]).order_by(
            'sorttype', 'pkg__pkgname',
            'pkg__arch__name', 'pkg__repo__name')
        if not self.arch.agnostic:
            # make sure we match architectures if possible
            requiredby = requiredby.filter(
                pkg__arch__in=self.applicable_arches())

        # if we can use ALPM, ensure our returned Depend objects abide by the
        # version comparison operators they may specify
        alpm = AlpmAPI()
        if alpm.available:
            provides = self.provides.all()
            new_rqd = []
            for dep in requiredby:
                if not dep.comparison or not dep.version:
                    # no comparison/version, so always let it through
                    new_rqd.append(dep)
                elif self.pkgname == dep.name:
                    # depends on this package, so check it directly
                    if alpm.compare_versions(self.full_version, dep.comparison, dep.version):
                        new_rqd.append(dep)
                else:
                    # it must be a provision of ours at this point
                    for provide in (p for p in provides if p.name == dep.name):
                        if alpm.compare_versions(provide.version, dep.comparison, dep.version):
                            new_rqd.append(dep)
                            break
            requiredby = new_rqd

        # sort out duplicate packages; this happens if something has a double
        # versioned depend such as a kernel module
        requiredby = [next(iter(vals)) for _, vals in groupby(requiredby, lambda x: x.pkg.id)]
        if not requiredby:
            return requiredby

        # do we have duplicate pkgbase values for non-primary depends?
        # if so, filter it down to base packages only
        def grouper(depend):
            p = depend.pkg
            return (depend.deptype, p.pkgbase, p.repo.testing, p.repo.staging)

        filtered = []
        for (typ, _, _, _), dep_pkgs in groupby(requiredby, grouper):
            dep_pkgs = list(dep_pkgs)
            if typ == 'D' or len(dep_pkgs) == 1:
                filtered.extend(dep_pkgs)
            else:
                filtered.append(DependStandin(dep_pkgs))

        # find another package by this name in a different testing or staging
        # repo; if we can't, we can short-circuit some checks

templates/devel/admin_log.html
{% extends "admin/base_site.html" %}
{% load i18n static %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/dashboard.css" %}" />{% endblock %}

{% block breadcrumbs %}<div class="breadcrumbs"><a href="/admin/">{% trans 'Home' %}</a>{% if title %} &rsaquo; {{ title }}{% endif %}</div>{% endblock %}

{% block content %}
<div id="content-main">
    <div class="module">
{% load log %}
{% if log_user %}
{% get_admin_log 100 as admin_log for_user log_user %}
{% else %}
{% get_admin_log 100 as admin_log %}
{% endif %}
{% if not admin_log %}
<p>{% trans 'None available' %}</p>
{% else %}
<table id="change-history">
    <thead>
        <tr>
            <th scope="col">{% trans 'Date/time' %}</th>
            <th scope="col">{% trans 'User' %}</th>
            <th>Type</th>
            <th>Object</th>
            <th scope="col">{% trans 'Action' %}</th>
        </tr>
    </thead>
    <tbody>
        {% for entry in admin_log %}
        <tr>
            <th scope="row">{{ entry.action_time|date:"Y-m-d H:i" }}</th>
            {% if log_user %}
            <td>{{ entry.user.username }}{% if entry.user.get_full_name %} ({{ entry.user.get_full_name }}){% endif %}</td>
            {% else %}
            <td><a href="{{ entry.user.username }}/">{{ entry.user.username }}</a>{% if entry.user.get_full_name %} ({{ entry.user.get_full_name }}){% endif %}</td>
            {% endif %}
            <td>
                {% if entry.content_type %}
                <span>{% filter capfirst %}{% trans entry.content_type.name %}{% endfilter %}</span>
                {% else %}
                <span>{% trans 'Unknown content' %}</span>
                {% endif %}
            </td>
            <td>
                <span class="{% if entry.is_addition %}addlink{% endif %}{% if entry.is_change %}changelink{% endif %}{% if entry.is_deletion %}deletelink{% endif %}"></span>
                {% if entry.is_deletion %}
                {{ entry.object_repr }}
                {% else %}
                <a href="{{ entry.get_admin_url }}">{{ entry.object_repr }}</a>
                {% endif %}
            </td>
            <td>{{ entry.change_message }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endif %}
    </div>
</div>
{% endblock %}

templates/devel/clock.html
{% extends "base.html" %}
{% load static %}
{% load flags %}
{% load tz %}

{% block title %}Arch Linux - Developer World Clocks{% endblock %}

{% block head %}<link rel="stylesheet" type="text/css" href="{% static "flags/fam.css" %}" media="screen" />{% endblock %}

{% block content %}
<div id="dev-clocks-box" class="box">
    <h2>Developer World Clocks</h2>

    <p>This page helps prevent you from waking a sleeping developer. It also
    depends on developers keeping the time zone information up to date, so if
    you see 'UTC' listed, pester them to update their settings.</p>
    <p>The "Last Action" column shows the last time this developer has done
    something we know about. Considered dates for each developer include:</p>
    <ul>
        <li>Build date of a package in the repositories</li>
        <li>Last login to the developer side of this site</li>
        <li>Admin log entry on this site (e.g., adding a donor, modifying a
        mirror)</li>
        <li>Post date of a news item</li>
        <li>Signing off on a package</li>
        <li>Flagging a package out-of-date</li>
    </ul>
    <p>
    Current UTC Time: {{ utc_now|date:"Y-m-d H:i T" }}
    </p>

    <table id="clocks-table" class="results">
        <thead>
            <tr>
                <th>Developer</th>
                <th>Username</th>
                <th>Alias</th>
                <th>Last Action</th>
                <th>Location</th>
                <th>Time Zone</th>
                <th>Current Time</th>
            </tr>
        </thead>
        <tbody>
            {% for dev in developers %}
            <tr>
                <td><a href="mailto:{{ dev.email }}">{{ dev.get_full_name }}</a></td>
                <td>{{ dev.username }}</td>
                <td>{{ dev.userprofile.alias }}</td>
                <td>{{ dev.last_action }}</td>
                <td>{% country_flag dev.userprofile.country %}{{ dev.userprofile.location }}</td>
                <td>{{ dev.userprofile.time_zone }}</td>
                <td>{{ utc_now|timezone:dev.userprofile.time_zone|date:"Y-m-d H:i T" }}<span class="hide"> {{ dev.userprofile.time_zone }}</span></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

{% block script_block %}
{% load cdn %}{% jquery %}{% jquery_tablesorter %}
<script type="text/javascript" src="{% static "archweb.js" %}"></script>
<script type="text/javascript" nonce={{ CSP_NONCE }}>
$(document).ready(function() {
    $("#clocks-table:has(tbody tr)").tablesorter({
        widgets: ['zebra'],
        sortLocaleCompare: true,
        sortList: [[0,0]],
        headers: { 4: { sorter: false } }
    });
});
</script>
{% endblock %}

templates/devel/profile.html
{% extends "base.html" %}
{% load static %}

{% block title %}Arch Linux - Edit Profile{% endblock %}

{% block content %}
<div id="dev-edit-profile" class="box">

    <h2>Developer Profile</h2>

    <form id="edit-profile-form" enctype="multipart/form-data" method="post" action="">{% csrf_token %}
        <p><em>Note:</em> This is the public information shown on the developer
        and/or package maintainer profiles page, so please be appropriate with the information
        you provide here.</p>
        <fieldset>
            <p><label>Username:</label>
            <strong>{{ user.username }}</strong></p>
            {{ form.as_p }}
        </fieldset>
        <fieldset>
            {{ profile_form.as_p }}
        </fieldset>
        <p><label></label> <input title="Save changes" type="submit" value="Save" /></p>
    </form>

</div>
{% endblock %}

templates/devel/stats.html
{% load cache %}

{% cache 60 dev-dash-by-arch %}
<div id="dash-by-arch" class="box">

    <h2>Stats by Architecture</h2>

    <table id="stats-by-arch" class="results dash-stats">
        <thead>
            <tr>
                <th class="key">Arch</th>
                <th># Packages</th>
                <th># Flagged</th>
            </tr>
        </thead>
        <tbody>
            {% for arch in arches %}
                <tr>
                    <td>{{ arch.name }}</td>
                    <td><a href="/packages/?arch={{ arch.name }}"
                            title="View all packages for the {{ arch.name }} architecture">
                            <strong>{{ arch.total_ct }}</strong> packages</a></td>
                    <td><a href="/packages/?arch={{ arch.name }}&amp;flagged=Flagged"
                            title="View all flagged packages for the {{ arch.name }} architecture">
                            <strong>{{ arch.flagged_ct }}</strong> packages</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>{# #dash-by-arch #}
{% endcache %}

{% cache 60 dev-dash-by-repo %}
<div id="dash-by-repo" class="box">

    <h2>Stats by Repository</h2>

    <table id="stats-by-repo" class="results dash-stats">
        <thead>
            <tr>
                <th class="key">Repository</th>
                <th># Packages</th>
                <th># Flagged</th>
                <th># Maintainers</th>
            </tr>
        </thead>
        <tbody>
            {% for repo in repos %}
                <tr>
                    <td>{{ repo.name }}</td>
                    <td><a href="/packages/?repo={{ repo.name }}"
                            title="View all packages in the {{ repo.name }} repository">
                            <strong>{{ repo.total_ct }}</strong> packages</a></td>
                    <td><a href="/packages/?repo={{ repo.name }}&amp;flagged=Flagged"
                            title="View all flagged packages in the {{ repo.name }} repository">
                            <strong>{{ repo.flagged_ct }}</strong> packages</a></td>
                    <td><strong>{{ repo.maintainer_ct }}</strong> maintainers</td>
                </tr>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>{# dash-by-arch #}
{% endcache %}

{% cache 60 dev-dash-by-developer %}
<div id="dash-by-developer" class="box">

    <h2>Stats by Developer</h2>

    {% if perms.main.change_package %}
    <p><a href="/packages/stale_relations/">Look for stale relations</a></p>
    {% endif %}

    <table id="stats-by-maintainer" class="results dash-stats">
        <thead>
            <tr>
                <th class="key">Maintainer</th>
                <th># Maintained</th>
                <th># Flagged</th>
                <th># Last Packager</th>
            </tr>
            <tr class="even">
                <td><em>Orphan/Unknown</em></td>
                <td><a href="/packages/?maintainer=orphan"
                        title="View all orphan packages">
                        <strong>{{ orphan.package_count }}</strong> packages</a>
                </td>
                <td><a href="/packages/?maintainer=orphan&amp;flagged=Flagged"
                        title="View all flagged orphan packages">
                        <strong>{{ orphan.flagged_count }}</strong> packages</a>
                </td>
                <td><a href="/packages/?packager=unknown"
                        title="View all packages last updated by unknown">
                        <strong>{{ orphan.updated_count }}</strong> packages</a>
                </td>
            </tr>
        </thead>
        <tbody>
            {% for maint in maintainers %}
                <tr>
                    <td>{{ maint.get_full_name }}</td>
                    <td><a href="/packages/?maintainer={{ maint.username }}"
                            title="View all packages maintained by {{ maint.get_full_name }}">
                            <strong>{{ maint.package_count }}</strong> packages</a>
                    </td>
                    <td><a href="/packages/?maintainer={{ maint.username }}&amp;flagged=Flagged"
                            title="View all flagged packages maintained by {{ maint.get_full_name }}">
                            <strong>{{ maint.flagged_count }}</strong> packages</a>
                    </td>
                    <td><a href="/packages/?packager={{ maint.username }}"
                            title="View all packages last updated by {{ maint.get_full_name }}">
                            <strong>{{ maint.updated_count }}</strong> packages</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>{# #dash-by-developer #}
{% endcache %}

templates/devel/tier0_mirror.html
{% extends "base.html" %}
{% load static %}

{% block title %}Arch Linux - Tier0 Mirror{% endblock %}

{% block content %}
<div class="box">

    <h2>Tier 0 Mirror usage information</h2>
    <p>Arch Linux Tier 0 mirror on <a href="https://repos.archlinux.org">repos.archlinux.org</a> which can be used if to obtain the absolute latest packages. The mirror is protected with an HTTP Basic Auth password unique per Staff member.</p>
    {% if mirror_url %}
      <code id="serverinfo">Server = {{ mirror_url }}</code> <button id="copybutton">Copy to clipboard</button>

      <form enctype="multipart/form-data" method="post" action="">{% csrf_token %}
        <p><label></label> <input title="Generate repository access token" type="submit" value="Re-generate access token" /></p>
      </form>
    {% else %}
      <form enctype="multipart/form-data" method="post" action="">{% csrf_token %}
        <p><label></label> <input title="Generate repository access token" type="submit" value="Generate access token" /></p>
      </form>
    {% endif %}
</div>
{% endblock %}

{% block script_block %}
<script type="text/javascript" nonce={{ CSP_NONCE }} defer>
  const copybutton = document.getElementById('copybutton');
  copybutton.addEventListener('click', function() {
    const text = document.getElementById('serverinfo').textContent;
    navigator.clipboard.writeText(text)
      .then(() => {
          // TODO: implement userfriendly snackbar
    })
    .catch(err => {
      console.error('Error in copying text: ', err);
    });


  });


</script>
{% endblock %}