news/urls.py
from django.contrib.auth.decorators import permission_required
from django.urls import path, re_path

from main.utils import cache_user_page

from .views import (
    NewsCreateView,
    NewsDeleteView,
    NewsDetailView,
    NewsEditView,
    NewsListView,
    preview,
    view_redirect,
)

urlpatterns = [
    path('', cache_user_page(317)(NewsListView.as_view()), name='news-list'),

    path('preview/', preview),
    # old news URLs, permanent redirect view so we don't break all links
    re_path(r'^(?P<object_id>\d+)/$', view_redirect),

    path('add/',
         permission_required('news.add_news')(NewsCreateView.as_view())),
    re_path(r'^(?P<slug>[-\w]+)/$',
            cache_user_page(317)(NewsDetailView.as_view())),
    re_path(r'^(?P<slug>[-\w]+)/edit/$',
            permission_required('news.change_news')(NewsEditView.as_view())),
    re_path(r'^(?P<slug>[-\w]+)/delete/$',
            permission_required('news.delete_news')(NewsDeleteView.as_view())),
]

# vim: set ts=4 sw=4 et:

urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.sitemaps import views as sitemap_views
from django.urls import include, path, re_path
from django.views.decorators.cache import cache_page
from django.views.generic import TemplateView

import devel.urls
import mirrors.urls
import mirrors.urls_mirrorlist
import news.urls
import packages.urls
import packages.urls_groups
import packages.views
import planet.views
import public.views
import releng.urls
import sitemaps
import todolists.urls
import visualize.urls
from feeds import NewsFeed, PackageFeed, PackageUpdatesFeed, PlanetFeed, ReleaseFeed

our_sitemaps = {
    'base':           sitemaps.BaseSitemap,
    'news':           sitemaps.NewsSitemap,
    'packages':       sitemaps.PackagesSitemap,
    'package-files':  sitemaps.PackageFilesSitemap,
    'package-groups': sitemaps.PackageGroupsSitemap,
    'split-packages': sitemaps.SplitPackagesSitemap,
    'releases':       sitemaps.ReleasesSitemap,
    'todolists':      sitemaps.TodolistSitemap,
}

news_sitemaps = {'news': sitemaps.RecentNewsSitemap}

urlpatterns = []

# Public pages
urlpatterns.extend([
    path('', public.views.index, name='index'),
    path('about/', TemplateView.as_view(template_name='public/about.html'), name='page-about'),
    path('art/',   TemplateView.as_view(template_name='public/art.html'), name='page-art'),
    path('donate/', public.views.donate, name='page-donate'),
    path('download/', public.views.download, name='page-download'),
    path('master-keys/', public.views.keys, name='page-keys'),
    path('master-keys/json/', public.views.keys_json, name='pgp-keys-json'),
    re_path(r'^people/(?P<slug>[-\w]+)/$', public.views.people, name='people'),
    path('planet/', planet.views.index, name='planet'),
])

# Feeds patterns, used below
feeds_patterns = [
    path('', public.views.feeds, name='feeds-list'),
    path('news/', cache_page(311)(NewsFeed())),
    path('packages/', cache_page(313)(PackageFeed())),
    re_path(r'^packages/(added|removed)/$', cache_page(313)(PackageUpdatesFeed())),
    re_path(r'^packages/(added|removed)/(?P<arch>[A-z0-9]+)/$', cache_page(313)(PackageUpdatesFeed())),
    re_path(r'^packages/(added|removed)/all/(?P<repo>[A-z0-9\-]+)/$', cache_page(313)(PackageUpdatesFeed())),
    re_path(r'^packages/(added|removed)/(?P<arch>[A-z0-9]+)/(?P<repo>[A-z0-9\-]+)/$',
            cache_page(313)(PackageUpdatesFeed())),
    re_path(r'^packages/(?P<arch>[A-z0-9]+)/$', cache_page(313)(PackageFeed())),
    re_path(r'^packages/all/(?P<repo>[A-z0-9\-]+)/$', cache_page(313)(PackageFeed())),
    re_path(r'^packages/(?P<arch>[A-z0-9]+)/(?P<repo>[A-z0-9\-]+)/$', cache_page(313)(PackageFeed())),
    path('releases/', cache_page(317)(ReleaseFeed())),
    path('planet/', cache_page(317)(PlanetFeed()), name='planet-feed'),
]

# Old planet.archlinux.org redirects, to be removed once people have migrated.
urlpatterns.extend([
    path('planet/rss20.xml', cache_page(317)(PlanetFeed())),
    path('planet/atom.xml', cache_page(317)(PlanetFeed())),
])

# Includes and other remaining stuff
urlpatterns.extend([
    path('admin/', admin.site.urls),
    path('devel/', include(devel.urls)),
    path('feeds/', include(feeds_patterns)),
    path('groups/', include(packages.urls_groups)),
    path('mirrorlist/', include(mirrors.urls_mirrorlist)),
    path('mirrors/', include(mirrors.urls)),
    path('news/', include(news.urls)),
    path('packages/', include(packages.urls)),
    path('releng/', include(releng.urls)),
    path('todo/', include(todolists.urls)),
    path('visualize/', include(visualize.urls)),
    path('opensearch/packages/', packages.views.opensearch, name='opensearch-packages'),
    path('opensearch/packages/suggest', packages.views.opensearch_suggest, name='opensearch-packages-suggest'),
])

# Sitemaps
urlpatterns.extend([
    path('sitemap.xml', cache_page(1831)(sitemap_views.index),
         {'sitemaps': our_sitemaps, 'sitemap_url_name': 'sitemaps'}),
    re_path(r'^sitemap-(?P<section>.+)\.xml$', cache_page(1831)(sitemap_views.sitemap),
            {'sitemaps': our_sitemaps, 'template_name': 'sitemaps/sitemap.xml'},
            name='sitemaps'),
    path('news-sitemap.xml', cache_page(1831)(sitemap_views.sitemap),
         {'sitemaps': news_sitemaps, 'template_name': 'sitemaps/news_sitemap.xml'},
         name='news-sitemap'),
])

# Authentication
urlpatterns.extend([
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
])

# django-toolbar
if settings.DEBUG_TOOLBAR:  # pragma: no cover
    import debug_toolbar
    urlpatterns.extend([
        path('__debug__/', include(debug_toolbar.urls)),
    ])

# prometheus metrics
if settings.PROMETHEUS_METRICS:  # pragma :no cover
    urlpatterns.extend([
        path('', include('django_prometheus.urls')),
    ])


# displays all archweb urls
def show_urls(urllist=urlpatterns, depth=0):  # pragma: no cover
    for entry in urllist:
        print("  " * depth, entry.regex.pattern)
        if hasattr(entry, 'url_patterns'):
            show_urls(entry.url_patterns, depth + 1)

# vim: set ts=4 sw=4 et:

news/models.py
from django.contrib.auth.models import User
from django.contrib.sites.models import Site
from django.db import models
from django.db.models.signals import pre_save
from django.utils.safestring import mark_safe
from django.utils.timezone import now

from main.utils import parse_markdown


class News(models.Model):
    slug = models.SlugField(max_length=255, unique=True)
    author = models.ForeignKey(User, related_name='news_author',
                               on_delete=models.PROTECT)
    postdate = models.DateTimeField("post date", db_index=True)
    last_modified = models.DateTimeField(editable=False, db_index=True)
    title = models.CharField(max_length=255)
    guid = models.CharField(max_length=255, editable=False)
    content = models.TextField()
    safe_mode = models.BooleanField(default=True)
    send_announce = models.BooleanField(default=True)

    def get_absolute_url(self):
        return '/news/%s/' % self.slug

    def html(self):
        return mark_safe(parse_markdown(self.content, not self.safe_mode))

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'news'
        verbose_name_plural = 'news'
        get_latest_by = 'postdate'
        ordering = ('-postdate',)


def set_news_fields(sender, **kwargs):
    news = kwargs['instance']
    current_time = now()
    news.last_modified = current_time
    if not news.postdate:
        news.postdate = current_time
        # http://diveintomark.org/archives/2004/05/28/howto-atom-id
        news.guid = f"tag:{Site.objects.get_current()},{current_time.strftime('%Y-%m-%d')}:{news.get_absolute_url()}"


pre_save.connect(set_news_fields, sender=News, dispatch_uid="news.models")

# vim: set ts=4 sw=4 et:

news/views.py
from django import forms
from django.conf import settings
from django.core.mail import EmailMessage
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.template import loader
from django.views.decorators.http import require_POST
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from main.utils import find_unique_slug, parse_markdown

from .models import News


class NewsForm(forms.ModelForm):
    class Meta:
        model = News
        exclude = ('id', 'slug', 'author', 'postdate', 'safe_mode')


class NewsDetailView(DetailView):
    queryset = News.objects.all().select_related('author')
    template_name = "news/view.html"


class NewsListView(ListView):
    queryset = News.objects.all().select_related('author').defer('content')
    template_name = "news/list.html"
    paginate_by = 50


class NewsCreateView(CreateView):
    model = News
    form_class = NewsForm
    template_name = "news/add.html"

    def form_valid(self, form):
        # special logic, we auto-fill the author and slug fields
        newsitem = form.save(commit=False)
        newsitem.author = self.request.user
        newsitem.slug = find_unique_slug(News, newsitem.title)
        newsitem.save()
        if newsitem.send_announce:
            ctx = {
                'news': newsitem,
            }
            headers = {}
            if settings.MAILMAN_PASSWORD:
                headers['Approved'] = settings.MAILMAN_PASSWORD
            template = loader.get_template('news/news_email_notification.txt')
            author = newsitem.author.get_full_name()
            from_ = f'"Arch Linux: Recent news updates: {author}" <{settings.ANNOUNCE_EMAIL}>'
            EmailMessage(
                subject=f'[arch-announce] {newsitem.title}',
                body=template.render(ctx),
                from_email=from_,
                to=[settings.ANNOUNCE_EMAIL],
                headers=headers).send()
        return super(NewsCreateView, self).form_valid(form)


class NewsEditView(UpdateView):
    model = News
    form_class = NewsForm
    template_name = "news/add.html"


class NewsDeleteView(DeleteView):
    model = News
    template_name = "news/delete.html"
    success_url = "/news/"


def view_redirect(request, object_id):
    newsitem = get_object_or_404(News, pk=object_id)
    return redirect(newsitem, permanent=True)


@require_POST
def preview(request):
    data = request.POST.get('data', '')
    markup = parse_markdown(data)
    return HttpResponse(markup)

# vim: set ts=4 sw=4 et:

templates/news/add.html
{% extends "base.html" %}
{% load static %}
{% block title %}Arch Linux - News: {% if form.instance.id %}Edit{% else %}Add{% endif %} Article{% endblock %}

{% block content %}
<div id="news-add-article" class="box">

    {% if form.instance.id %}
    <h2>News: Edit Article</h2>
    {% else %}
    <h2>News: Add Article</h2>
    {% endif %}
    <p>Every news post needs to have a corresponding draft <strong>submitted</strong> to
    arch-dev-public and wait for feedback for at least 24 hours unless:</p>
    <ol>
      <li>It is urgent (and would be too late after 24 hours)</li>
      <li>There are strong reasons for the team member posting the draft to
	      believe that it should not be visible to the public before it is
	      announced. In this second case, the draft should be submitted to
      the staff@lists.archlinux.org mailing list instead.</li>
    </ol>

    <p>News articles are formatted using
    <a href="http://daringfireball.net/projects/markdown/syntax">Markdown syntax</a>.
    Please use this syntax if at all possible over raw HTML, which can be used
    if Markdown doesn't support what you would like to do. Before posting, you
    are highly encouraged to use the <strong>Preview</strong> button to check
    your work.  Javascript must be enabled to use it, but it will render the
    news item exactly as it will appear on the news view page.</p>
    <form id="newsform" method="post">{% csrf_token %}
        <fieldset>
            {{ form.as_p }}
        </fieldset>
        <p>
        <label></label>
        <input title="Save changes" type="submit" value="Save" />
        <input id="news-preview-button" title="Preview" type="button" value="Preview" />
        </p>
    </form>
</div>

<div id="news-preview" class="news-article box">
    <h2>News Preview: <span id="news-preview-title"></span></h2>
    <div id="news-preview-data" class="article-content"></div>
</div>
<script type="text/javascript" nonce={{ CSP_NONCE }} defer>
function onPreviewButtonClick(event) {
	event.preventDefault();

	const formData = new FormData();
	formData.append('data', document.querySelector('#id_content').value);
	formData.append('csrfmiddlewaretoken', document.querySelector('#newsform input[name=csrfmiddlewaretoken]').value);

	fetch('/news/preview/', {
		method: 'POST',
		body: formData,
	}).then(response => response.text())
	.then(data => {
		document.querySelector('#news-preview-data').innerHTML = data;
		document.querySelector('#news-preview').style.display = 'block';
		document.querySelector('#news-preview-title').innerHTML = document.querySelector('#id_title').value;
	}).catch(error => {
		console.error(error);
	});
}

const previewButton = document.getElementById('news-preview-button');
previewButton.addEventListener('click', onPreviewButtonClick);
</script>
{% endblock %}

templates/news/delete.html
{% extends "base.html" %}
{% block title %}Arch Linux - Delete News{% endblock %}

{% block content %}
<div id="news-delete-entry" class="box">

    <h2>News: Delete Entry Confirmation</h2>

    <p>You are about to delete the following news item:</p>

    <blockquote>
        <strong>{{news}}</strong>
    </blockquote>

    <p>Are you sure?</p>

    <form method="post">{% csrf_token %}
        <input title="Delete this article" id="delete" name="delete"
        type="submit" value="Delete" /></p>
    </form>

</div>
{% endblock %}

templates/news/list.html
{% extends "base.html" %}

{% block title %}Arch Linux - News{% endblock %}

{% block head %}
<link rel="alternate" type="application/rss+xml" title="Arch Linux News Updates" href="/feeds/news/" />
{% endblock %}

{% block content %}
<div id="news-article-list" class="box">

    <h2>Arch Linux News Archives</h2>

    {% if perms.news.add_news %}
    <ul class="admin-actions">
        <li><a href="/news/add/" title="Add a news item">Add News Item</a></li>
    </ul>
    {% endif %}

    {% include "news/paginator.html" %}

    <table id="article-list" class="results">
        <thead>
            <tr>
                <th>Published</th>
                <th>Title</th>
                <th>Author</th>
                {% if perms.news.change_news %}
                <th></th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for item in news_list %}
            <tr>
                <td>{{ item.postdate|date:"Y-m-d" }}</td>
                <td class="wrap"><a href="{{ item.get_absolute_url }}"
                        title="View: {{ item.title }}">{{ item.title }}</a></td>
                <td>{{ item.author.get_full_name }}</td>
                {% if perms.news.change_news %}
                <td>
                    <a href="{{ item.get_absolute_url }}edit/"
                        title="Edit: {{ item.title }}">Edit</a>
                    {% endif %}
                    {% if perms.news.delete_news %}
                    &nbsp;&nbsp;<a href="{{ item.get_absolute_url }}delete/"
                        title="Delete: {{ item.title }}">Delete</a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>

    {% include "news/paginator.html" %}
</div>
{% endblock %}

templates/news/paginator.html
{% if is_paginated %}
<div class="pagination">
    <p>{{ paginator.count }} news items, viewing page {{ page_obj.number }} of {{ paginator.num_pages }}.</p>
    <p class="news-nav">
    {% if page_obj.has_previous %}
    <a class="prev" href="?page={{ page_obj.previous_page_number }}"
        title="Go to previous page" rel="prev">&lt; Prev</a>
    {% endif %}
    {% for num in paginator.page_range %}
    {% if num == page_obj.number %}
    <span>{{ num }}</span>
    {% else %}
    <a href="?page={{ num }}" title="Go to page {{ num }}">{{ num }}</a>
    {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
    <a class="next" href="?page={{ page_obj.next_page_number }}"
        title="Go to next page" rel="next">Next &gt;</a>
    {% endif %}
    </p>
</div>
{% endif %}

templates/news/view.html
{% extends "base.html" %}
{% block title %}Arch Linux - News: {{ news.title }}{% endblock %}

{% block content %}
<div itemscope itemtype="http://schema.org/Article" class="news-article box">
    <h2 itemprop="headline">{{ news.title }}</h2>
    <meta itemprop="dateCreated" content="{{ news.postdate|date:"Y-m-d" }}"/>
    <meta itemprop="datePublished" content="{{ news.postdate|date:"Y-m-d" }}"/>
    <meta itemprop="dateModified" content="{{ news.last_modified|date:"Y-m-d" }}"/>
    <meta itemprop="inLanguage" content="en"/>
    <meta itemprop="wordCount" content="{{ news.content|wordcount }}"/>
    <div class="itemprop" itemprop="author" itemscope itemtype="http://schema.org/Person">
        <meta itemprop="name" content="{{ news.author.get_full_name|escape }}"/>
    </div>
    <div class="itemprop" itemprop="publisher" itemscope itemtype="http://schema.org/Organization">
        <meta itemprop="name" content="Arch Linux"/>
    </div>

    {% if perms.news.change_news %}
    <ul class="admin-actions">
        <li><a href="edit/" title="Edit this article">Edit News Item</a></li>
        {% if perms.news.delete_news %}
        <li><a href="delete/" title="Delete this article">Delete News Item</a></li>
        {% endif %}
    </ul>
    {% endif %}

    <p class="article-info">{{ news.postdate|date:"Y-m-d" }} - {{ news.author.get_full_name }}</p>

    <div class="article-content" itemprop="articleBody">{{ news.html }}</div>
</div>
{% endblock %}